### ISSUE TITLE
Multiple coordinate spaces?

### ISSUE THREAD

**Issue by igoronzy** [lidaof/g3d#38]
I tried to map my own 3D model to a .g3d file. Some of the chromosomes appear as "mini" chromosomes in the middle of the nucleus, surrounded by larger chromosomes (as if they are being mapped to a different coordinate space). 
I double checked that all the bond lengths between adjacent bins are approximately the same throughout the nucleus. But in the three-D viewer, there are two different bond lengths (a "mini" for 4 chromosomes and a normal for all other chromosomes). 
When I load the xyz coordinates in pymol, everything appears normal.
Any ideas what might be going on?
![mini2](https://user-images.githubusercontent.com/30717081/187994087-526396d1-df4d-49f5-90cf-abead4b19002.JPG)

**Comment by lidaof** [comment]
Hi @igoronzy I guess this might happen due to a method I applied trying to make the 3d coordinate numbers in a similar range, so for the original x, y and z, they are transformed with following code:
```js
let x = data[hap][chr].x[0];
let y = data[hap][chr].y[0];
let z = data[hap][chr].z[0];
const maxXYZ = Math.max(Math.abs(x), Math.abs(y), Math.abs(z));
const scale = getScale3d(maxXYZ);
x /= scale;
y /= scale;
z /= scale;
```

the function:
```js
const getScale3d = (num) => {
    const mag = Math.floor(Math.log10(num));
    return 10 ** (mag - 1);
};
```

are the numbers for your chromosomes different in terms of scales?
thanks for reporting this by the way!

**Comment by igoronzy** [comment]
Yes, your right! The chromosomes that got miniaturized had coordinates >10, whereas most other coordinates were <10. Is there a potential hack around?

**Comment by lidaof** [comment]
Hi @igoronzy i guess you can easily time every number with 10 (or 100) to get them all at similar scale?
